// src/const/eco.ts
export type EcoTags = {
  main: string;
  sub?: string;
};

export const ecoLookup: Record<string, EcoTags> = {
  // A00–A99: Flank & Queen's Pawn Systems
  A00: { main: 'Uncommon Opening' },
  A01: { main: 'Larsen' },
  A02: { main: "Bird's" },
  A03: { main: "Bird's" },
  A04: { main: 'Réti' },
  A05: { main: 'Réti' },
  A06: { main: 'Réti' },
  A07: { main: "King's Indian Attack" },
  A08: { main: "King's Indian Attack" },
  A09: { main: 'Réti' },
  A10: { main: 'English' },
  A11: { main: 'English', sub: 'Caro-Kann Defense' },
  A12: { main: 'English', sub: 'Caro-Kann Defense' },
  A13: { main: 'English', sub: 'Symmetrical' },
  A14: { main: 'English', sub: 'Neo-Catatlan declined' },
  A15: { main: 'English', sub: 'Anglo-Indian' },
  A16: { main: 'English', sub: 'Anglo-Indian' },
  A17: { main: 'English', sub: 'Anglo-Indian' },
  A18: { main: 'English', sub: 'Anglo-Indian' },
  A19: { main: 'English', sub: 'Anglo-Indian' },
  A20: { main: 'English', sub: "King's English" },
  A21: { main: 'English', sub: "King's English" },
  A22: { main: 'English', sub: "King's English" },
  A23: { main: 'English', sub: 'Bremen' },
  A24: { main: 'English', sub: 'Bremen' },
  A25: { main: 'English', sub: 'Closed' },
  A26: { main: 'English', sub: 'Closed' },
  A27: { main: 'English', sub: 'Three Knights' },
  A28: { main: 'English', sub: 'Four Knights' },
  A29: { main: 'English', sub: 'Four Knights' },
  A30: { main: 'English', sub: 'Symmetrical' },
  A31: { main: 'English', sub: 'Symmetrical' },
  A32: { main: 'English', sub: 'Symmetrical' },
  A33: { main: 'English', sub: 'Symmetrical' },
  A34: { main: 'English', sub: 'Symmetrical' },
  A35: { main: 'English', sub: 'Symmetrical' },
  A36: { main: 'English', sub: 'Symmetrical' },
  A37: { main: 'English', sub: 'Symmetrical' },
  A38: { main: 'English', sub: 'Symmetrical' },
  A39: { main: 'English', sub: 'Symmetrical' },
  A40: { main: "Queen's Pawn" },
  A41: { main: "Queen's Pawn" },
  A42: { main: 'Modern' },
  A43: { main: 'Benoni', sub: 'Old Benoni' },
  A44: { main: 'Benoni', sub: 'Old Benoni' },
  A45: { main: "Queen's Pawn" },
  A46: { main: "Queen's Pawn" },
  A47: { main: "Queen's Indian" },
  A48: { main: "King's Indian" },
  A49: { main: "King's Indian" },
  A50: { main: "Queen's Pawn" },
  A51: { main: 'Budapest', sub: 'Gambit' },
  A52: { main: 'Budapest', sub: 'Gambit' },
  A53: { main: 'Old Indian' },
  A54: { main: 'Old Indian' },
  A55: { main: 'Old Indian' },
  A56: { main: 'Benoni', sub: 'Modern Benoni' },
  A57: { main: 'Benko Gambit' },
  A58: { main: 'Benko Gambit' },
  A59: { main: 'Benko Gambit' },
  A60: { main: 'Benoni', sub: 'Modern Benoni' },
  A61: { main: 'Benoni', sub: 'Modern Benoni' },
  A62: { main: 'Benoni', sub: 'Fianchetto' },
  A63: { main: 'Benoni', sub: 'Fianchetto' },
  A64: { main: 'Benoni', sub: 'Fianchetto' },
  A65: { main: 'Benoni', sub: 'Schmid' },
  A66: { main: 'Benoni', sub: 'Schmid' },
  A67: { main: 'Benoni', sub: 'Taimanov' },
  A68: { main: 'Benoni', sub: 'Four Pawns' },
  A69: { main: 'Benoni', sub: 'Four Pawns' },
  A70: { main: 'Benoni', sub: 'Classical' },
  A71: { main: 'Benoni', sub: 'Classical' },
  A72: { main: 'Benoni', sub: 'Classical' },
  A73: { main: 'Benoni', sub: 'Classical' },
  A74: { main: 'Benoni', sub: 'Classical' },
  A75: { main: 'Benoni', sub: 'Classical' },
  A76: { main: 'Benoni', sub: 'Classical' },
  A77: { main: 'Benoni', sub: 'Classical' },
  A78: { main: 'Benoni', sub: 'Classical' },
  A79: { main: 'Benoni', sub: 'Classical' },
  A80: { main: 'Dutch', sub: 'General' },
  A81: { main: 'Dutch', sub: 'Modern' },
  A82: { main: 'Dutch', sub: 'Modern' },
  A83: { main: 'Dutch', sub: 'Staunton' },
  A84: { main: 'Dutch', sub: 'Classical' },
  A85: { main: 'Dutch', sub: 'Classical' },
  A86: { main: 'Dutch', sub: 'Leningrad' },
  A87: { main: 'Dutch', sub: 'Leningrad' },
  A88: { main: 'Dutch', sub: 'Leningrad' },
  A89: { main: 'Dutch', sub: 'Leningrad' },
  A90: { main: 'Dutch', sub: 'Stonewall' },
  A91: { main: 'Dutch', sub: 'Stonewall' },
  A92: { main: 'Dutch', sub: 'Stonewall' },
  A93: { main: 'Dutch', sub: 'Stonewall' },
  A94: { main: 'Dutch', sub: 'Stonewall' },
  A95: { main: 'Dutch', sub: 'Stonewall' },
  A96: { main: 'Dutch', sub: 'Stonewall' },
  A97: { main: 'Dutch', sub: 'Stonewall' },
  A98: { main: 'Dutch', sub: 'Stonewall' },
  A99: { main: 'Dutch', sub: 'Stonewall' },

  // Continue with B00–E99 in next updates.

  // B00–B99: 1.e4 e6 / e5 / c5 systems
  B00: { main: 'Kings pawn' },
  B01: { main: 'Scandinavian', sub: 'Modern' },
  B02: { main: 'Alekhine', sub: 'Main Line' },
  B03: { main: 'Alekhine', sub: 'Four Pawns' },
  B04: { main: 'Alekhine', sub: 'Modern' },
  B05: { main: 'Alekhine', sub: 'Exchange' },
  B06: { main: 'Robatsch', sub: 'Modern' },
  B07: { main: 'Pirc', sub: 'Classical' },
  B08: { main: 'Pirc', sub: 'Classical' },
  B09: { main: 'Pirc', sub: 'Austrian' },

  B10: { main: 'Caro-Kann', sub: 'Closed' },
  B11: { main: 'Caro-Kann', sub: 'Two Knights' },
  B12: { main: 'Caro-Kann', sub: 'Advance' },
  B13: { main: 'Caro-Kann', sub: 'Exchange' },
  B14: { main: 'Caro-Kann', sub: 'Panov-Botvinnik' },
  B15: { main: 'Caro-Kann', sub: 'Classical' },
  B16: { main: 'Caro-Kann', sub: 'Bronstein-Larsen' },
  B17: { main: 'Caro-Kann', sub: 'Karpov' },
  B18: { main: 'Caro-Kann', sub: 'Classical' },
  B19: { main: 'Caro-Kann', sub: 'Classical' },

  B20: { main: 'Sicilian' },
  B21: { main: 'Sicilian', sub: 'Smith-Morra' },
  B22: { main: 'Sicilian', sub: 'Alapin' },
  B23: { main: 'Sicilian', sub: 'Closed' },
  B24: { main: 'Sicilian', sub: 'Closed' },
  B25: { main: 'Sicilian', sub: 'Closed' },
  B26: { main: 'Sicilian', sub: 'Closed' },
  B27: { main: 'Sicilian', sub: 'Closed' },
  B28: { main: 'Sicilian', sub: "O'Kelly" },
  B29: { main: 'Sicilian', sub: 'Nimzowitsch' },

  B30: { main: 'Sicilian', sub: 'Rossolimo' },
  B31: { main: 'Sicilian', sub: 'Rossolimo' },
  B32: { main: 'Sicilian', sub: 'Classical' },
  B33: { main: 'Sicilian', sub: 'Sveshnikov' },
  B34: { main: 'Sicilian', sub: 'Accelerated Dragon' },
  B35: { main: 'Sicilian', sub: 'Accelerated Dragon' },
  B36: { main: 'Sicilian', sub: 'Accelerated Dragon' },
  B37: { main: 'Sicilian', sub: 'Dragadorf' },
  B38: { main: 'Sicilian', sub: 'Dragon' },
  B39: { main: 'Sicilian', sub: 'Dragon' },

  B40: { main: 'Sicilian', sub: 'Kan' },
  B41: { main: 'Sicilian', sub: 'Kan' },
  B42: { main: 'Sicilian', sub: 'Kan' },
  B43: { main: 'Sicilian', sub: 'Taimanov' },
  B44: { main: 'Sicilian', sub: 'Taimanov' },
  B45: { main: 'Sicilian', sub: 'Taimanov' },
  B46: { main: 'Sicilian', sub: 'Taimanov' },
  B47: { main: 'Sicilian', sub: 'Taimanov' },
  B48: { main: 'Sicilian', sub: 'Taimanov' },
  B49: { main: 'Sicilian', sub: 'Taimanov' },

  B50: { main: 'Sicilian' },
  B51: { main: 'Sicilian', sub: 'Tank Variation' },
  B52: { main: 'Sicilian', sub: 'Canal Attack' },
  B53: { main: 'Sicilian', sub: 'Chekhover' },
  B54: { main: 'Sicilian', sub: 'Scheveningen' },
  B55: { main: 'Sicilian', sub: 'Scheveningen' },
  B56: { main: 'Sicilian', sub: 'Scheveningen' },
  B57: { main: 'Sicilian', sub: 'Sozin' },
  B58: { main: 'Sicilian', sub: 'Sozin' },
  B59: { main: 'Sicilian', sub: 'Sozin' },

  B60: { main: 'Sicilian', sub: 'Richter-Rauzer' },
  B61: { main: 'Sicilian', sub: 'Richter-Rauzer' },
  B62: { main: 'Sicilian', sub: 'Richter-Rauzer' },
  B63: { main: 'Sicilian', sub: 'Richter-Rauzer' },
  B64: { main: 'Sicilian', sub: 'Scheveningen' },
  B65: { main: 'Sicilian', sub: 'Scheveningen' },
  B66: { main: 'Sicilian', sub: 'Scheveningen' },
  B67: { main: 'Sicilian', sub: 'Scheveningen' },
  B68: { main: 'Sicilian', sub: 'Scheveningen' },
  B69: { main: 'Sicilian', sub: 'Scheveningen' },

  B70: { main: 'Sicilian', sub: 'Dragon' },
  B71: { main: 'Sicilian', sub: 'Dragon' },
  B72: { main: 'Sicilian', sub: 'Dragon' },
  B73: { main: 'Sicilian', sub: 'Dragon' },
  B74: { main: 'Sicilian', sub: 'Dragon' },
  B75: { main: 'Sicilian', sub: 'Dragon' },
  B76: { main: 'Sicilian', sub: 'Dragon' },
  B77: { main: 'Sicilian', sub: 'Dragon' },
  B78: { main: 'Sicilian', sub: 'Dragon' },
  B79: { main: 'Sicilian', sub: 'Dragon' },

  B80: { main: 'Sicilian', sub: 'Scheveningen' },
  B81: { main: 'Sicilian', sub: 'Scheveningen' },
  B82: { main: 'Sicilian', sub: 'Scheveningen' },
  B83: { main: 'Sicilian', sub: 'Scheveningen' },
  B84: { main: 'Sicilian', sub: 'Scheveningen' },
  B85: { main: 'Sicilian', sub: 'Scheveningen' },
  B86: { main: 'Sicilian', sub: 'Sozin' },
  B87: { main: 'Sicilian', sub: 'Sozin' },
  B88: { main: 'Sicilian', sub: 'Sozin' },
  B89: { main: 'Sicilian', sub: 'Sozin' },

  B90: { main: 'Sicilian', sub: 'Najdorf' },
  B91: { main: 'Sicilian', sub: 'Najdorf' },
  B92: { main: 'Sicilian', sub: 'Najdorf' },
  B93: { main: 'Sicilian', sub: 'Najdorf' },
  B94: { main: 'Sicilian', sub: 'Najdorf' },
  B95: { main: 'Sicilian', sub: 'Najdorf' },
  B96: { main: 'Sicilian', sub: 'Najdorf' },
  B97: { main: 'Sicilian', sub: 'Najdorf' },
  B98: { main: 'Sicilian', sub: 'Najdorf' },
  B99: { main: 'Sicilian', sub: 'Najdorf' },

  C00: { main: 'French' },
  C01: { main: 'French', sub: 'Exchange' },
  C02: { main: 'French', sub: 'Advance' },
  C03: { main: 'French', sub: 'Tarrasch' },
  C04: { main: 'French', sub: 'Tarrasch' },
  C05: { main: 'French', sub: 'Tarrasch' },
  C06: { main: 'French', sub: 'Tarrasch' },
  C07: { main: 'French', sub: 'Tarrasch' },
  C08: { main: 'French', sub: 'Tarrasch' },
  C09: { main: 'French', sub: 'Tarrasch' },
  C10: { main: 'French' },
  C11: { main: 'French' },
  C12: { main: 'French', sub: 'McCutcheon' },
  C13: { main: 'French' },
  C14: { main: 'French', sub: 'Classical' },
  C15: { main: 'French', sub: 'Winawer' },
  C16: { main: 'French', sub: 'Winawer' },
  C17: { main: 'French', sub: 'Winawer' },
  C18: { main: 'French', sub: 'Winawer' },
  C19: { main: 'French', sub: 'Winawer' },

  C20: { main: "King's Pawn" },
  C21: { main: 'Center Game' },
  C22: { main: 'Center Game' },
  C23: { main: "Bishop's Opening" },
  C24: { main: "Bishop's Opening" },
  C25: { main: 'Vienna' },
  C26: { main: 'Vienna' },
  C27: { main: 'Vienna' },
  C28: { main: 'Vienna' },
  C29: { main: 'Vienna Gambit' },

  C30: { main: "King's Gambit Declined" },
  C31: { main: "King's Gambit Declined" },
  C32: { main: "King's Gambit Declined" },
  C33: { main: "King's Gambit Accepted" },
  C34: { main: "King's Gambit Accepted" },
  C35: { main: "King's Gambit Accepted", sub: 'Cunningham' },
  C36: { main: "King's Gambit Accepted", sub: 'Abbazia' },
  C37: { main: "King's Gambit Accepted" },
  C38: { main: "King's Gambit Accepted" },
  C39: { main: "King's Gambit Accepted" },

  C40: { main: "King's Knight Opening" },
  C41: { main: 'Philidor' },
  C42: { main: 'Petrov' },
  C43: { main: 'Petrov', sub: 'Modern Attack' },
  C44: { main: "King's Pawn" },
  C45: { main: 'Scotch Game' },
  C46: { main: 'Three Knights' },
  C47: { main: 'Four Knights', sub: 'Scotch' },
  C48: { main: 'Four Knights', sub: 'Scotch' },
  C49: { main: 'Four Knights', sub: 'Scotch' },

  C50: { main: 'Italian Game' },
  C51: { main: 'Italian', sub: 'Evans Gambit' },
  C52: { main: 'Italian', sub: 'Evans Gambit' },
  C53: { main: 'Giuoco Piano' },
  C54: { main: 'Giuoco Piano' },
  C55: { main: 'Italian', sub: 'Two Knights' },
  C56: { main: 'Italian', sub: 'Two Knights' },
  C57: { main: 'Italian', sub: 'Two Knights' },
  C58: { main: 'Italian', sub: 'Two Knights' },
  C59: { main: 'Italian', sub: 'Two Knights' },

  C60: { main: 'Ruy Lopez' },
  C61: { main: 'Ruy Lopez', sub: "Bird's" },
  C62: { main: 'Ruy Lopez', sub: 'Old Steinitz' },
  C63: { main: 'Ruy Lopez', sub: 'Schliemann' },
  C64: { main: 'Ruy Lopez', sub: 'Classical' },
  C65: { main: 'Ruy Lopez', sub: 'Berlin' },
  C66: { main: 'Ruy Lopez' },
  C67: { main: 'Ruy Lopez' },
  C68: { main: 'Ruy Lopez', sub: 'Exchange' },
  C69: { main: 'Ruy Lopez', sub: 'Exchange' },

  C70: { main: 'Ruy Lopez' },
  C71: { main: 'Ruy Lopez', sub: 'Modern Steinitz' },
  C72: { main: 'Ruy Lopez', sub: 'Modern Steinitz' },
  C73: { main: 'Ruy Lopez', sub: 'Modern Steinitz' },
  C74: { main: 'Ruy Lopez', sub: 'Modern Steinitz' },
  C75: { main: 'Ruy Lopez', sub: 'Modern Steinitz' },
  C76: { main: 'Ruy Lopez', sub: 'Modern Steinitz' },
  C77: { main: 'Ruy Lopez', sub: 'Morphy Defense' },
  C78: { main: 'Ruy Lopez' },
  C79: { main: 'Ruy Lopez', sub: 'Steinitz Deferred' },

  C80: { main: 'Ruy Lopez', sub: 'Open' },
  C81: { main: 'Ruy Lopez', sub: 'Open' },
  C82: { main: 'Ruy Lopez', sub: 'Open' },
  C83: { main: 'Ruy Lopez', sub: 'Open' },
  C84: { main: 'Ruy Lopez', sub: 'Closed' },
  C85: { main: 'Ruy Lopez', sub: 'Exchange Deferred' },
  C86: { main: 'Ruy Lopez', sub: 'Worrall Attack' },
  C87: { main: 'Ruy Lopez' },
  C88: { main: 'Ruy Lopez' },
  C89: { main: 'Ruy Lopez', sub: 'Marshall' },

  C90: { main: 'Ruy Lopez', sub: 'Closed' },
  C91: { main: 'Ruy Lopez', sub: 'Closed' },
  C92: { main: 'Ruy Lopez', sub: 'Closed' },
  C93: { main: 'Ruy Lopez', sub: 'Closed' },
  C94: { main: 'Ruy Lopez', sub: 'Closed' },
  C95: { main: 'Ruy Lopez', sub: 'Closed' },
  C96: { main: 'Ruy Lopez', sub: 'Closed' },
  C97: { main: 'Ruy Lopez', sub: 'Closed' },
  C98: { main: 'Ruy Lopez', sub: 'Closed' },
  C99: { main: 'Ruy Lopez', sub: 'Closed' },

  D00: { main: "Queen's Pawn Game" },
  D01: { main: "Queen's Pawn", sub: 'Richter-Veresov Attack' },
  D02: { main: "Queen's Pawn Game" },
  D03: { main: "Queen's Pawn", sub: 'Torre Attack' },
  D04: { main: "Queen's Pawn Game" },
  D05: { main: "Queen's Pawn Game" },
  D06: { main: "Queen's Gambit Declined" },
  D07: { main: "Queen's Gambit Declined", sub: 'Chigorin' },
  D08: { main: "Queen's Gambit Declined", sub: 'Albin Countergambit' },
  D09: { main: "Queen's Gambit Declined", sub: 'Albin Countergambit' },

  D10: { main: "Queen's Gambit Declined", sub: 'Slav' },
  D11: { main: "Queen's Gambit Declined", sub: 'Slav' },
  D12: { main: "Queen's Gambit Declined", sub: 'Slav' },
  D13: { main: "Queen's Gambit Declined", sub: 'Exchange Variation' },
  D14: { main: "Queen's Gambit Declined", sub: 'Exchange Variation' },
  D15: { main: "Queen's Gambit Declined", sub: 'Slav' },
  D16: { main: "Queen's Gambit Declined", sub: 'Slav' },
  D17: { main: "Queen's Gambit Declined", sub: 'Slav' },
  D18: { main: "Queen's Gambit Declined", sub: 'Slav' },
  D19: { main: "Queen's Gambit Declined", sub: 'Slav' },

  D20: { main: "Queen's Gambit Accepted" },
  D21: { main: "Queen's Gambit Accepted" },
  D22: { main: "Queen's Gambit Accepted" },
  D23: { main: "Queen's Gambit Accepted" },
  D24: { main: "Queen's Gambit Accepted" },
  D25: { main: "Queen's Gambit Accepted" },
  D26: { main: "Queen's Gambit Accepted" },
  D27: { main: "Queen's Gambit Accepted", sub: 'Classical' },
  D28: { main: "Queen's Gambit Accepted", sub: 'Classical' },
  D29: { main: "Queen's Gambit Accepted", sub: 'Classical' },

  D30: { main: "Queen's Gambit Declined" },
  D31: { main: "Queen's Gambit Declined" },
  D32: { main: "Queen's Gambit Declined", sub: 'Tarrasch' },
  D33: { main: "Queen's Gambit Declined", sub: 'Tarrasch' },
  D34: { main: "Queen's Gambit Declined", sub: 'Tarrasch' },
  D35: { main: "Queen's Gambit Declined" },
  D36: { main: "Queen's Gambit Declined", sub: 'Exchange Variation' },
  D37: { main: "Queen's Gambit Declined" },
  D38: { main: "Queen's Gambit Declined", sub: 'Ragozin' },
  D39: { main: "Queen's Gambit Declined", sub: 'Ragozin' },

  D40: { main: "Queen's Gambit Declined", sub: 'Semi-Tarrasch' },
  D41: { main: "Queen's Gambit Declined", sub: 'Semi-Tarrasch' },
  D42: { main: "Queen's Gambit Declined", sub: 'Semi-Tarrasch' },
  D43: { main: "Queen's Gambit Declined", sub: 'Semi-Slav' },
  D44: { main: "Queen's Gambit Declined", sub: 'Semi-Slav' },
  D45: { main: "Queen's Gambit Declined", sub: 'Semi-Slav' },
  D46: { main: "Queen's Gambit Declined", sub: 'Semi-Slav' },
  D47: { main: "Queen's Gambit Declined", sub: 'Semi-Slav' },
  D48: { main: "Queen's Gambit Declined", sub: 'Meran' },
  D49: { main: "Queen's Gambit Declined", sub: 'Meran' },

  D50: { main: "Queen's Gambit Declined" },
  D51: { main: "Queen's Gambit Declined" },
  D52: { main: "Queen's Gambit Declined" },
  D53: { main: "Queen's Gambit Declined" },
  D54: { main: "Queen's Gambit Declined", sub: 'Anti-Neo-Orthodox' },
  D55: { main: "Queen's Gambit Declined" },
  D56: { main: "Queen's Gambit Declined" },
  D57: { main: "Queen's Gambit Declined", sub: 'Lasker' },
  D58: { main: "Queen's Gambit Declined", sub: 'Tartakower' },
  D59: { main: "Queen's Gambit Declined", sub: 'Tartakower' },

  D60: { main: "Queen's Gambit Declined", sub: 'Orthodox' },
  D61: { main: "Queen's Gambit Declined", sub: 'Rubinstein' },
  D62: { main: "Queen's Gambit Declined", sub: 'Rubinstein' },
  D63: { main: "Queen's Gambit Declined", sub: 'Orthodox' },
  D64: { main: "Queen's Gambit Declined", sub: 'Rubinstein' },
  D65: { main: "Queen's Gambit Declined", sub: 'Rubinstein' },
  D66: { main: "Queen's Gambit Declined", sub: 'Bd3 Line' },
  D67: { main: "Queen's Gambit Declined", sub: 'Bd3 Line' },
  D68: { main: "Queen's Gambit Declined", sub: 'Classical' },
  D69: { main: "Queen's Gambit Declined", sub: 'Classical' },

  D70: { main: 'Neo-Grünfeld' },
  D71: { main: 'Neo-Grünfeld' },
  D72: { main: 'Neo-Grünfeld' },
  D73: { main: 'Neo-Grünfeld' },
  D74: { main: 'Neo-Grünfeld' },
  D75: { main: 'Neo-Grünfeld' },
  D76: { main: 'Neo-Grünfeld' },
  D77: { main: 'Neo-Grünfeld' },
  D78: { main: 'Neo-Grünfeld' },
  D79: { main: 'Neo-Grünfeld' },

  D80: { main: 'Grünfeld' },
  D81: { main: 'Grünfeld', sub: 'Russian' },
  D82: { main: 'Grünfeld' },
  D83: { main: 'Grünfeld', sub: 'Gambit' },
  D84: { main: 'Grünfeld', sub: 'Gambit Accepted' },
  D85: { main: 'Grünfeld' },
  D86: { main: 'Grünfeld', sub: 'Exchange' },
  D87: { main: 'Grünfeld', sub: 'Exchange' },
  D88: { main: 'Grünfeld', sub: 'Spassky Variation' },
  D89: { main: 'Grünfeld' },

  D90: { main: 'Grünfeld' },
  D91: { main: 'Grünfeld' },
  D92: { main: 'Grünfeld' },
  D93: { main: 'Grünfeld' },
  D94: { main: 'Grünfeld' },
  D95: { main: 'Grünfeld' },
  D96: { main: 'Grünfeld', sub: 'Russian' },
  D97: { main: 'Grünfeld', sub: 'Russian' },
  D98: { main: 'Grünfeld', sub: 'Russian' },
  D99: { main: 'Grünfeld', sub: 'Smyslov' },
  E00: { main: "Queen's Pawn Game" },
  E01: { main: 'Catalan', sub: 'Closed' },
  E02: { main: 'Catalan', sub: 'Open' },
  E03: { main: 'Catalan', sub: 'Open' },
  E04: { main: 'Catalan', sub: 'Open' },
  E05: { main: 'Catalan', sub: 'Open' },
  E06: { main: 'Catalan', sub: 'Closed' },
  E07: { main: 'Catalan', sub: 'Closed' },
  E08: { main: 'Catalan', sub: 'Closed' },
  E09: { main: 'Catalan', sub: 'Closed' },

  E10: { main: "Queen's Pawn Game" },
  E11: { main: 'Bogo-Indian' },
  E12: { main: "Queen's Indian" },
  E13: { main: "Queen's Indian", sub: 'Main Line' },
  E14: { main: "Queen's Indian" },
  E15: { main: "Queen's Indian" },
  E16: { main: "Queen's Indian" },
  E17: { main: "Queen's Indian" },
  E18: { main: "Queen's Indian", sub: 'Old Main Line' },
  E19: { main: "Queen's Indian", sub: 'Old Main Line' },

  E20: { main: 'Nimzo-Indian' },
  E21: { main: 'Nimzo-Indian', sub: 'Three Knights' },
  E22: { main: 'Nimzo-Indian', sub: 'Spielmann' },
  E23: { main: 'Nimzo-Indian', sub: 'Spielmann' },
  E24: { main: 'Nimzo-Indian', sub: 'Sämisch' },
  E25: { main: 'Nimzo-Indian', sub: 'Sämisch' },
  E26: { main: 'Nimzo-Indian', sub: 'Sämisch' },
  E27: { main: 'Nimzo-Indian', sub: 'Sämisch' },
  E28: { main: 'Nimzo-Indian', sub: 'Sämisch' },
  E29: { main: 'Nimzo-Indian', sub: 'Sämisch' },

  E30: { main: 'Nimzo-Indian', sub: 'Leningrad' },
  E31: { main: 'Nimzo-Indian', sub: 'Leningrad' },
  E32: { main: 'Nimzo-Indian', sub: 'Classical' },
  E33: { main: 'Nimzo-Indian', sub: 'Classical' },
  E34: { main: 'Nimzo-Indian', sub: 'Noa' },
  E35: { main: 'Nimzo-Indian', sub: 'Noa' },
  E36: { main: 'Nimzo-Indian', sub: 'Classical' },
  E37: { main: 'Nimzo-Indian', sub: 'Classical' },
  E38: { main: 'Nimzo-Indian', sub: 'Classical' },
  E39: { main: 'Nimzo-Indian', sub: 'Pirc' },

  E40: { main: 'Nimzo-Indian' },
  E41: { main: 'Nimzo-Indian' },
  E42: { main: 'Nimzo-Indian', sub: 'Rubinstein' },
  E43: { main: 'Nimzo-Indian', sub: 'Fischer' },
  E44: { main: 'Nimzo-Indian', sub: 'Fischer' },
  E45: { main: 'Nimzo-Indian', sub: 'Bronstein' },
  E46: { main: 'Nimzo-Indian' },
  E47: { main: 'Nimzo-Indian' },
  E48: { main: 'Nimzo-Indian' },
  E49: { main: 'Nimzo-Indian', sub: 'Botvinnik' },

  E50: { main: 'Nimzo-Indian' },
  E51: { main: 'Nimzo-Indian' },
  E52: { main: 'Nimzo-Indian' },
  E53: { main: 'Nimzo-Indian' },
  E54: { main: 'Nimzo-Indian', sub: 'Gligoric' },
  E55: { main: 'Nimzo-Indian', sub: 'Gligoric' },
  E56: { main: 'Nimzo-Indian' },
  E57: { main: 'Nimzo-Indian' },
  E58: { main: 'Nimzo-Indian' },
  E59: { main: 'Nimzo-Indian' },

  E60: { main: "King's Indian" },
  E61: { main: "King's Indian" },
  E62: { main: "King's Indian", sub: 'Fianchetto' },
  E63: { main: "King's Indian", sub: 'Panno' },
  E64: { main: "King's Indian", sub: 'Yugoslav' },
  E65: { main: "King's Indian", sub: 'Yugoslav' },
  E66: { main: "King's Indian", sub: 'Yugoslav' },
  E67: { main: "King's Indian", sub: 'Fianchetto' },
  E68: { main: "King's Indian", sub: 'Classical' },
  E69: { main: "King's Indian", sub: 'Classical' },

  E70: { main: "King's Indian" },
  E71: { main: "King's Indian", sub: 'Makagonov' },
  E72: { main: "King's Indian" },
  E73: { main: "King's Indian" },
  E74: { main: "King's Indian", sub: 'Averbakh' },
  E75: { main: "King's Indian", sub: 'Averbakh' },
  E76: { main: "King's Indian", sub: 'Four Pawns' },
  E77: { main: "King's Indian", sub: 'Four Pawns' },
  E78: { main: "King's Indian", sub: 'Four Pawns' },
  E79: { main: "King's Indian", sub: 'Four Pawns' },

  E80: { main: "King's Indian", sub: 'Sämisch' },
  E81: { main: "King's Indian", sub: 'Sämisch' },
  E82: { main: "King's Indian", sub: 'Sämisch' },
  E83: { main: "King's Indian", sub: 'Sämisch' },
  E84: { main: "King's Indian", sub: 'Sämisch' },
  E85: { main: "King's Indian", sub: 'Sämisch' },
  E86: { main: "King's Indian", sub: 'Sämisch' },
  E87: { main: "King's Indian", sub: 'Sämisch' },
  E88: { main: "King's Indian", sub: 'Sämisch' },
  E89: { main: "King's Indian", sub: 'Sämisch' },

  E90: { main: "King's Indian" },
  E91: { main: "King's Indian" },
  E92: { main: "King's Indian" },
  E93: { main: "King's Indian", sub: 'Petrosian' },
  E94: { main: "King's Indian", sub: 'Orthodox' },
  E95: { main: "King's Indian", sub: 'Orthodox' },
  E96: { main: "King's Indian", sub: 'Orthodox' },
  E97: { main: "King's Indian" },
  E98: { main: "King's Indian", sub: 'Taimanov' },
  E99: { main: "King's Indian", sub: 'Taimanov' },
};
