export const greetings = [
  "It's time to fix blunders and chew gum.",
  'Check your blunders at the door.',
  'Blunder-slaying season is open.',
  'No mercy. Just blunders to fix.',
  'The blunders missed you.',
  'Time to clean up, one move at a time.',
  'Fewer mistakes. More glory.',
  'The blunders never stood a chance.',
  'The board awaits.',
  'Grab a juicer. It’s cleanup time.',
  'Outwit. Outplay. Outblunder.',
  'Blunder today, brilliance tomorrow.',
  "Forget the past—unless it's on move 27.",
  'You. Me. Stockfish. Let’s dance.',
  'One blunder closer to greatness.',
  'The grind is real.',
  'Tactical debt? Time to pay up.',
  'The eval bar believes in you.',
  'Refuse to hang. Refuse to tilt.',
  'Fewer facepalms. More fist pumps.',
  'Upgrade in progress… don’t disturb.',
  'Leave no pawn behind.',
  'You brought pawns to a knight fight?',
  'From blunder to thunder.',
  'The truth lies at depth 20.',
  'Clean lines. Dirty tactics.',
  'Don’t think. Just fix.',
  "Today's sacrifice: your blunders.",
  'Better moves. Better you.',
  "A Queen's work is never done.",
  'May your blunders be few and your rooks connected.',
  'Every blunder is a lesson in disguise.',
  'Do or do not. There is no blunder.',
  'Blunder? Nah, it’s a deep positional idea.',
  'Gotham saw it. Stockfish screamed.',
  'Take, take, take... take back?',
  'Oh no… my Elo.',
  'Play the board, not the eval bar.',
  'Blunders? I call them story arcs.',
  'Live by the sword, die by the fork.',
  'May the fork be with you.',
  'Et tu, bishop?',
  'What doesn’t mate you makes you stronger.',
  'Keep calm and castle queenside.',
  'In the end, the pawns remember everything.',
  'Big threats come in small pawns.',
  'Rooks? Where we’re going, we don’t need rooks.',
  'I came, I saw, I hung blundered.',
  'Say hello to my little tactic.',
  'One does not simply walk into a fork.',
  'Nobody puts bishop in the corner.',
];
