export const greetings = [
  "It's time to fix blunders and chew gum.",
  'Check your blunders at the door.',
  'Blunder-slaying season is open.',
  'No mercy. Just blunders to fix.',
  'The blunders missed you.',
  'Time to clean up, one move at a time.',
  'Fewer mistakes. More glory.',
  'The blunders never stood a chance.',
  'The board awaits.',
  'Grab a juicer. It’s cleanup time.',
  'Outwit. Outplay. Outblunder.',
  'Blunder today, brilliance tomorrow.',
  "Forget the past—unless it's on move 27.",
  'You. Me. Stockfish. Let’s dance.',
  'One blunder closer to greatness.',
  'The grind is real.',
  'Tactical debt? Time to pay up.',
  'The eval bar believes in you.',
  'Refuse to hang. Refuse to tilt.',
  'Fewer facepalms. More fist pumps.',
  'Leave no pawn behind.',
  'You brought pawns to a knight fight?',
  'From blunder to thunder™',
  'The truth lies at depth 20.',
  'Clean lines. Dirty tactics.',
  'Don’t think. Just fix.',
  "Today's sacrifice: 1.e4.",
  'Better moves. Better you.',
  "A Queen's work is never done.",
  'May your blunders be few and your rooks connected.',
  'Every blunder is a lesson in disguise.',
  'Do or do not. There is no blunder.',
  'Blunder? Nah, it’s a deep positional idea.',
  'Gotham saw it. Stockfish screamed.',
  'Take, take, take... take back?',
  'Oh no… my Elo.',
  'Play the board, not the eval bar.',
  'Blunders? I call them story arcs.',
  'Live by the sword, die by the fork.',
  'May the fork be with you.',
  'Et tu, bishop?',
  'What doesn’t mate you makes you stronger.',
  'Keep calm and castle queenside.',
  'In the end, the pawns remember everything.',
  'Big threats come in small pawns.',
  'Pawns? Where we’re going, we don’t need pawns.',
  'I came, I saw, I blundered.',
  'Say hello to my little tactic.',
  'One does not simply walk into a fork.',
  'Nobody puts bishop in the corner.',
  'Bluners are just unpolished moves.',
  'Every blunder is a step towards mastery.',
  'Blunders, like wine, get better with age.',
  'Chess is 99% tactics and 1% blunders.',
  'Blunders, Blunders, everywhere...',
  'I was completely winning...',
  'Blunders are just tactical hiccups.',
  'Just waiting for your turn...',
  'I love the smell of checkmate in the morning',
  'One small step for man, one giant knight hop for mankind!',
  'All quiet on the blunder front.',
  'Who you calling a blunder?',
  'Who you gonna call? Blunderbusters!',
  'The next move is brought to you by chaos.',
  'You had one job. Checkmate.',
  'Do blunders even lift?',
  'Make blunders great again.',
  'Sacked the queen. For content.',
  'Pawn to be wild.',
  'Fork yeah!',
  'Knightmare on blunder street.',
  'Game of Pawns.',
  'Bishop happens.',
  'You rook me all night long.',
  'Blunder? I prefer the term “creative oversight.”',
  'Blunders are just tactical experiments.',
  'Bishops assemble!',
  'I take it all back',
  'Houston, we have a blunder.',
  'Ain’t nobody got time for accuracy.',
  'I don’t always blunder, but when I do, it’s mate-in-one.',
  'Brain: Don’t do it. Me: Does it.',
  'POV: you see a ‘free pawn’ and lose a rook.',
  'Mistakes were made.',
  'Trust the process. Ignore the eval.',
  'That’s a you problem, Stockfish.',
  'Felt cute, might blunder later.',
  'Played a move. Regret is instant.',
  "King's just out for a walk.",
  'That was theory, right?',
  'Just vibing with my knight on the rim.',
  'Walking into discovered checks like it’s 1999.',
  'Sacrificed the exchange… unintentionally.',
  'In every loss, a lesson whispers.',
  'Does Stockfish dream of electric knights?',
  'You had me at en passant.',
  'I see dead pieces.',
  'Not all sacrifices are wrong.',
  'When life gives you pawns, promote them.',
  'You miss 100% of the mates you don’t see.',
  'When in Rome...Play the Italian.',
  'Pin it to Win it.',
  'King safety optional.',
  'From slip-ups to checkmates.',
  'Blunders fear your comeback.',
  'Castles don’t build themselves.',
  'Unleash your inner GM.',
  'Click. Drag. Repeat.',
];
