export const greetings = [
  "It's time to fix blunders and chew gum.",
  'Check your blunders at the door.',
  'Blunder-slaying season is open.',
  'No mercy. Just blunders to fix.',
  'The blunders missed you.',
  'Time to clean up, one move at a time.',
  'Fewer mistakes. More glory.',
  'The blunders never stood a chance.',
  'The board awaits.',
  'Grab a juicer. It’s cleanup time.',
  'Outwit. Outplay. Outblunder.',
  'Blunder today, brilliance tomorrow.',
  "Forget the past—unless it's on move 27.",
  'You. Me. Stockfish. Let’s dance.',
  'One blunder closer to greatness.',
  'The grind is real.',
  'Tactical debt? Time to pay up.',
  'The eval bar believes in you.',
  'Refuse to hang. Refuse to tilt.',
  'Fewer facepalms. More fist pumps.',
  'Upgrade in progress… don’t disturb.',
  'Leave no pawn behind.',
];
